In [1]:
import numpy as np

In [4]:
#Q1
#Using vander function in numpy
def Vander(x):
    print(np.vander(x, x.size,increasing = False))

In [5]:
x = np.array([1,2,3,4,5,6])
Vander(x)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


In [9]:
#Q2
def moving_avg(x, k):
    result = []
    for i in range(0,x.size-k+1):
        result.append(np.mean(x[i:i+k]))
    return result

In [10]:
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
moving_avg(x,3)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]